# -*- coding: utf-8 -*-
C = {}

C["vi"] = dict(
tag="Sinking Relationships",
deck_title="Sinking Relationships",
deck_sub="Độ bền của danh mục xuất khẩu Việt Nam ở cấp quan hệ thị trường × sản phẩm",
deck_kicker="Báo cáo tiến độ dữ liệu",
group=["Nhóm nghiên cứu", "Người trình bày: [điền tên]",
       "Thành viên: [điền tên]", "Dữ liệu: WITS / UN Comtrade · bản dựng 25/08/2026"],
outline_title="Nội dung",
outline=["Vì sao cần một bộ dữ liệu mới",
         "Đơn vị quan sát: quan hệ → spell → episode-năm",
         "Bản đồ dữ liệu: năm tầng và sáu khóa ghép",
         "Dữ liệu mô tả nói gì",
         "Chất lượng dữ liệu và các hạn chế",
         "Bốn khối phân tích và sáu quyết định cần chốt"],
sections=[("01","Vì sao cần một bộ dữ liệu mới","Tổng kim ngạch không cho biết danh mục bền đến đâu"),
          ("02","Đơn vị quan sát","Nếu nắm được spell_id × year thì mọi file đều có chỗ đứng"),
          ("03","Bản đồ dữ liệu","Năm tầng, sáu khóa ghép, mười ba module"),
          ("04","Dữ liệu mô tả nói gì","Kết quả chẩn đoán trên dữ liệu thật, chưa phải kết luận nghiên cứu"),
          ("05","Chất lượng và hạn chế","Nói trước những gì dữ liệu chưa làm được"),
          ("06","Bước tiếp theo","Bốn khối phân tích và sáu quyết định cần chốt")],

s4_title="Một quan hệ có thật: lớn dần rồi chết",
s4_note="Nguồn: analysis/episodes.csv — spell DEU_VNM_H0_620291_2005, đọc trực tiếp từ dữ liệu.",
s5_title="Vì sao không dùng số liệu thương mại thông thường",
s5_tbl=[["Số liệu thương mại thông thường","Bộ dữ liệu này"],
        ["Đơn vị: nước × năm, hoặc ngành × năm","Đơn vị: thị trường × nhóm sản phẩm × spell × năm"],
        ["Trả lời: Việt Nam bán được bao nhiêu","Trả lời: quan hệ nào sống được bao lâu, rủi ro đứt gãy nằm ở đâu"],
        ["Nhìn thấy: quy mô danh mục","Nhìn thấy: độ bền của danh mục"],
        ["Không nhìn thấy quan hệ đang chết","Ước lượng được xác suất một quan hệ chấm dứt"]],
s5_quote="Kim ngạch cho biết danh mục lớn đến đâu, không cho biết danh mục bền đến đâu.",
s5_chain="quan hệ → thời gian tồn tại → hazard đứt gãy → xác suất sống sót → cơ hội đã điều chỉnh rủi ro → quyết định danh mục",

s7_title="Đơn vị quan sát, đọc từ dữ liệu thật",
s7_note="Quan hệ = một thị trường nhập khẩu × một product_family. Sống trong năm khi nước nhập khẩu khai nhập ≥ 10.000 USD.",
s8_title="Ba file lõi và một quy ước dễ đọc sai",
s8_tbl=[["File","Một dòng là gì","Khóa","Quy mô"],
        ["analysis/spells.csv","một spell","spell_id","228.175 × 11"],
        ["analysis/episodes.csv","một spell trong một năm","spell_id + year","747.719 × 22"],
        ["analysis/panel_final.csv","episodes sau khi ghép hết covariate","spell_id + year","747.719 × 158"]],
s8_c1h="Quy ước năm sự kiện",
s8_c1=["event = 1 ở năm Y nghĩa là Y là năm cuối quan hệ còn sống;",
       "quan hệ chấm dứt ở Y+1.",
       "Hệ quả: chính sách năm 2025 phải căn với khoảng rủi ro dẫn tới cái chết 2025."],
s8_c2h="Vì sao không dùng mã HS6 thô",
s8_c2=["Mã HS đổi qua các phiên bản H1–H6.",
       "Pipeline quy về nền H0 rồi gom thành product_family ổn định,",
       "để tránh biến “HS đổi mã” thành “quan hệ chết rồi sinh lại”."],
s9_title="Ba loại kiểm duyệt và quy mô dữ liệu",
s9_kpi=[("147","thị trường nhập khẩu"),("4.621","nhóm sản phẩm"),("228.175","spell"),
        ("747.719","episode-năm"),("158","cột trong master panel")],
s9_cards=[("Left-censored","Spell đã sống ngay từ năm nền 2002 nên không biết thực sự bắt đầu khi nào. Các spell này bị loại khỏi mẫu survival.",1),
          ("Right-censored","Spell vẫn còn sống ở cuối cửa sổ quan sát. Giữ lại với event = 0. Có 57.689 spell, tương đương 25,3%.",0),
          ("Administrative censoring","Nước ngừng nộp dữ liệu thì kiểm duyệt hành chính, không ghi là chết. Sáu reporter: RUS, BLR, BGD, KNA, LCA, SLB.",2)],

s11_title="Bản đồ dữ liệu: năm tầng",
s11_tiers=[("Tầng 0","Định nghĩa mẫu","15 file · không vào panel",
            ["importers_vn.csv","importer_vn_all.csv","vn_partner_screen.csv","eu_tariff_mapping.csv","country_meta.csv"],1),
           ("Tầng 1","Lõi thương mại","dựng từ Comtrade + ngưỡng 10K",
            ["spells.csv","episodes.csv"],0),
           ("Tầng 2","13 module covariate","mỗi module gắn ở một khóa",
            ["fta_vn.csv","macro_panel_v2.csv","gravity_vn.csv","glpi.csv","complexity_*.csv","ttbd_vn*.csv","_ntm6/","cbam_products.csv","us_*.csv"],1),
           ("Tầng 3","Master panel","158 cột = 16 khối · 656 MB",
            ["panel_final.csv"],0),
           ("Tầng 4","Output chẩn đoán","kết quả, không phải biến giải thích",
            ["km_survival.csv","hazard_baseline.csv","threshold_sensitivity.csv"],2),
           ("Tầng 5","Code và tài liệu","tái lập và truy vết",
            ["scripts/ · 25 file","docs/ · 15 file"],1)],
s11_note="Mỗi file chỉ rơi vào một trong ba loại: định nghĩa đơn vị, gắn vào đơn vị, hoặc sinh ra từ đơn vị.",
s12_title="Sáu khóa ghép — và fixed effect nào sẽ nuốt biến đó",
s12_tbl=[["#","Khóa ghép","Module gắn ở khóa này","Bị fixed effect nào hấp thụ"],
         ["1","spell_id × year","đơn vị quan sát của panel","—"],
         ["2","importer × product_family × year","trade core, thuế lịch sử","biến thiên nhiều nhất, an toàn nhất"],
         ["3","importer × year","vĩ mô, FTA, gravity, LPI/GLPI, phòng vệ TM, NTM AVE, ECI/COI","chết nếu dùng importer × year FE"],
         ["4","product_family hoặc HS4 × year","PCI, phạm vi CBAM, miễn trừ thuế Mỹ","chết nếu dùng product FE"],
         ["5","importer × HS6 × year","NTM6","gần khóa 2, nhưng độ phủ theo năm yếu"],
         ["6","year","GEPU, 16 chỉ số giá, thuế Mỹ 2025, toàn bộ biến phía Việt Nam","chết hoàn toàn với year FE"]],
s12_note_h="Hệ quả của thiết kế một exporter",
s12_note="Vì exporter được khóa là Việt Nam, mọi biến phía exporter chỉ thay đổi theo năm — đây là hạn chế đã biết của thiết kế một exporter, không phải sơ suất.",
s13_title="Mười ba module, mỗi module một câu",
s13_tbl=[["Module","File chính","Khóa","Vai trò","Cảnh báo phải nói"],
         ["Thuế lịch sử","cột trong panel · TRAINS","2","core policy","chỉ 13 reporter khai đích danh VN"],
         ["FTA","fta_vn.csv · 3.528","3","core policy","biết có ưu đãi, không luôn biết đúng mức"],
         ["Thuế Mỹ 2025","6 file us_*","6 + 4","extension cú sốc","bốn quy ước — phải chọn một"],
         ["NTM HS6","_ntm6/ · 126 mảnh","5","robustness","chỉ 38% dòng khảo sát đúng năm"],
         ["NTM quy ra thuế","ntm_ave_vn.csv · 2.668","3","robustness","lát cắt 2017 kéo qua thời gian"],
         ["NTM cấp ngành","ntm_country/sector/by_type","3","dự phòng","khác khái niệm — không trộn"],
         ["Vĩ mô","macro_panel_v2.csv · 3.552","3","core: GDP","phần mở rộng để robustness"],
         ["Logistics xanh","glpi.csv · 3.552","3","robustness","bốn cách xây, xếp hạng khác nhau"],
         ["Gravity","gravity_vn.csv · 2.940","3","core: dist, contig","CEPII dừng ở 2021"],
         ["Phòng vệ thương mại","ttbd_vn*.csv","3","robustness","quan sát yếu sau 2015"],
         ["Độ phức tạp & sốc","complexity_*, shocks_annual","4 / 3 / 6","core: PCI","sốc chung chết với year FE"],
         ["CBAM","cbam_products.csv · 269","4","extension","chưa phải giá carbon"],
         ["EPI","epi_indicators_annual.csv","3","nguyên liệu GLPI","52 chỉ báo, không dùng thẳng"]],
s14_title="158 cột, đọc theo khối chứ không đọc theo tên biến",
s14_note="Master panel để lưu trữ đầy đủ và truy vết nguồn — không phải để đưa cả 158 biến vào một hồi quy. Mỗi mô hình chỉ rút một tập con.",

s16_note="Xác suất sống sót sau 1 năm 53,1% · 2 năm 38,9% · 5 năm 25,3% · 10 năm 18,9%.",
s17_note="Spell một năm là đặc tính thật của dữ liệu trade duration, không phải nhiễu cần xóa.",
s18_note="Nâng ngưỡng gấp 50 lần, tỷ lệ spell một năm chỉ giảm từ 55,3% xuống 41,9% — sẽ xử lý bằng phân tầng hoặc robustness.",
s19_note="Sau 2023 chưa đọc được như xu hướng: thuế TRAINS carry-forward và độ bất định báo cáo Comtrade còn cao.",
s20_note="Trung Quốc và Hoa Kỳ chiếm hơn 500 tỷ USD mỗi thị trường, nhưng chỉ khoảng 27% spell sống được từ 5 năm trở lên.",
s21_note="Quan hệ nhỏ chết sớm là quy luật rõ nhất trong dữ liệu — và cũng là biến có hazard ratio mạnh nhất ở mô hình baseline.",
s22_note="EU-27 cho bối cảnh thể chế thống nhất, có EVFTA làm cú sốc chính sách, và vẫn còn 148.442 episode-năm.",
s23_note="Đây là chẩn đoán cho thấy pipeline chạy được. Chưa khóa specification, fixed effects, clustering và timing — chưa được đọc như kết quả nghiên cứu.",

s25_note="Độ phủ cao không có nghĩa là đo đúng năm. NTM HS6 chỉ 38% dòng có khảo sát đúng năm, và 30% mượn ngược từ tương lai — phải đọc là “chưa đo được”, không phải “NTM thấp”.",
s26_title="Năm hạn chế phải nói trước khi bị hỏi",
s26=[("Thuế ưu đãi chưa đo đầy đủ",
      "Chỉ 13 reporter khai biểu thuế đích danh Việt Nam. Trong panel, 46,3% episode có FTA hiệu lực nhưng 81,8% trong số đó vẫn ghi thuế loại MFN — tức mức thuế thực tế có thể bị ghi cao hơn.",0),
     ("Thuế 2024–2025 là carry-forward",
      "TRAINS chưa công bố hai năm này; panel mang giá trị 2023 sang. Chỉ lớp thuế Mỹ 2025 có biến động chính sách thật.",0),
     ("NTM không phải chuỗi hằng năm",
      "File researcher bắt đầu từ 2010, các nước nộp theo lịch khảo sát rời rạc. 30% dòng có NTM mượn ngược từ kỳ khảo sát tương lai.",2),
     ("CBAM chưa phải giá carbon",
      "Chế độ chính thức bắt đầu 01/01/2026, sau cửa sổ panel. cbam_definitive = 0 trên toàn bộ dữ liệu hiện tại.",2),
     ("Survival không tự động là nhân quả",
      "Mô hình hazard mô tả hoặc dự báo mối liên hệ. Muốn nói chính sách gây ra đứt gãy cần identification strategy, treatment timing và counterfactual.",1)],
s26_rule="Ô trống không phải số 0: cột thuế Mỹ chỉ có nghĩa với importer là Hoa Kỳ, cột CBAM chỉ có nghĩa với thành viên EU theo từng năm.",

s28_title="Bốn khối phân tích và trạng thái thật",
s28_tbl=[["Khối","Câu hỏi","Dữ liệu dùng","Trạng thái"],
         ["1 · Survival","Quan hệ nào sống lâu hơn?","spells.csv · Kaplan–Meier","đã có mô tả sơ bộ"],
         ["2 · Hazard","Điều gì liên quan tới rủi ro đứt gãy?","panel · 5 lớp biến","pipeline chạy được, chưa khóa specification"],
         ["3 · Cú sốc chính sách","Tác động khác nhau ở đâu?","thuế, FTA/EVFTA, Brexit, NTM, CBAM, thuế Mỹ","dữ liệu sẵn, chưa chạy"],
         ["4 · Danh mục","Biết rủi ro rồi thì nên làm gì?","giá trị × xác suất sống sót dự báo","chưa định nghĩa được toán học"]],
s28_note="Cách nói đúng là “dữ liệu đã sẵn sàng để kiểm định”, không phải “nghiên cứu đã chứng minh”.",
s29_title="Sáu quyết định xin thầy chốt",
s29=[("01 · Đo lường","Network survivability định nghĩa bằng gì — tỷ lệ giá trị còn sống, xác suất tối thiểu của danh mục, hay expected loss dưới cú sốc?"),
     ("02 · Tối ưu hóa","Hàm mục tiêu là gì — tối đa xuất khẩu kỳ vọng, có phạt tập trung, hay đa mục tiêu?"),
     ("03 · Quyết định","Ngưỡng maintain / expand / reduce / enter / exit đặt ở đâu, và candidate universe dựng thế nào?"),
     ("04 · Kinh tế lượng","Specification chính: cloglog hay Cox, fixed effects nào, clustering nào, policy ở t hay t−1?"),
     ("05 · Phương pháp","Chọn cách xây GLPI nào làm bản chính, ba cách còn lại làm sensitivity?"),
     ("06 · Mẫu","Spell một năm: giữ trong mô hình chính, tách tầng, hay chỉ để robustness?")],
s17_t="Phân phối thời gian tồn tại",
s18_t="Độ nhạy theo ngưỡng 10.000 USD",
s19_t="Tỷ lệ đứt gãy theo năm",
s20_t="Thị trường lớn không phải thị trường bền",
s21_t="Giá trị và thời gian tồn tại đi cùng nhau",
s22_t="Phạm vi mẫu thực nghiệm",
s23_t="Hazard baseline — chẩn đoán sơ bộ",
s25_t="Độ phủ cao, nhưng thời điểm đo mới là vấn đề",
s26_rule_h="Quy tắc đọc dữ liệu",
thanks="Xin cảm ơn thầy",
thanks_sub="Toàn bộ số liệu trong slide được đọc trực tiếp từ analysis/ — không có con số nào chép lại từ tài liệu mô tả.",
)

C["en"] = dict(
tag="Sinking Relationships",
deck_title="Sinking Relationships",
deck_sub="The durability of Viet Nam's export portfolio at the market × product relationship level",
deck_kicker="Data Progress Report",
group=["Research group", "Presenter: [your name]",
       "Members: [names]", "Data: WITS / UN Comtrade · build of 25 Aug 2026"],
outline_title="Contents",
outline=["Why a new dataset was needed",
         "The unit of observation: relationship → spell → episode-year",
         "The data map: five tiers and six merge keys",
         "What the descriptive data shows",
         "Data quality and known limitations",
         "Four analysis blocks and six decisions to lock"],
sections=[("01","Why a new dataset was needed","Total export value says nothing about how durable the portfolio is"),
          ("02","The unit of observation","Once you hold spell_id × year, every file has a place"),
          ("03","The data map","Five tiers, six merge keys, thirteen modules"),
          ("04","What the descriptive data shows","Diagnostics on the real panel — not yet research findings"),
          ("05","Quality and limitations","State what the data cannot do before being asked"),
          ("06","Next steps","Four analysis blocks and six decisions to lock")],

s4_title="One real relationship: it grew, then it died",
s4_note="Source: analysis/episodes.csv — spell DEU_VNM_H0_620291_2005, read directly from the data.",
s5_title="Why conventional trade statistics are not enough",
s5_tbl=[["Conventional trade statistics","This dataset"],
        ["Unit: country × year, or sector × year","Unit: market × product family × spell × year"],
        ["Answers: how much Viet Nam sold","Answers: how long a relationship survives, where failure risk sits"],
        ["Shows: portfolio size","Shows: portfolio durability"],
        ["Cannot see a relationship dying","Estimates the probability a relationship ends"]],
s5_quote="Export value tells you how large the portfolio is, not how durable it is.",
s5_chain="relationship → duration → failure hazard → survival probability → risk-adjusted opportunity → portfolio decision",

s7_title="The unit of observation, read from real data",
s7_note="A relationship = one importing market × one product_family. Alive in a year when the importer reports ≥ USD 10,000 of imports.",
s8_title="Three core files and one convention that is easy to misread",
s8_tbl=[["File","What one row is","Key","Size"],
        ["analysis/spells.csv","one spell","spell_id","228,175 × 11"],
        ["analysis/episodes.csv","one spell in one year","spell_id + year","747,719 × 22"],
        ["analysis/panel_final.csv","episodes after all covariates are merged","spell_id + year","747,719 × 158"]],
s8_c1h="The event-year convention",
s8_c1=["event = 1 in year Y means Y is the last year the relationship was alive;",
       "the relationship ends in Y+1.",
       "Consequence: a 2025 policy must align with the risk interval leading to a 2025 failure."],
s8_c2h="Why not raw HS6 codes",
s8_c2=["HS codes change across revisions H1–H6.",
       "The pipeline maps everything back to the H0 base and groups codes into a stable product_family,",
       "so that “the HS code changed” is not read as “the relationship died and was reborn”."],
s9_title="Three kinds of censoring, and the size of the data",
s9_kpi=[("147","importing markets"),("4,621","product families"),("228,175","spells"),
        ("747,719","episode-years"),("158","columns in master panel")],
s9_cards=[("Left-censored","The spell was already alive in the 2002 base year, so its true start is unknown. These spells are dropped from the survival sample.",1),
          ("Right-censored","The spell is still alive at the end of the observation window. Kept with event = 0. There are 57,689 such spells — 25.3%.",0),
          ("Administrative censoring","When a country stops reporting, the spell is censored administratively rather than recorded as a death. Six reporters: RUS, BLR, BGD, KNA, LCA, SLB.",2)],

s11_title="The data map: five tiers",
s11_tiers=[("Tier 0","Sample definition","15 files · never enter the panel",
            ["importers_vn.csv","importer_vn_all.csv","vn_partner_screen.csv","eu_tariff_mapping.csv","country_meta.csv"],1),
           ("Tier 1","Trade core","built from Comtrade + the 10K threshold",
            ["spells.csv","episodes.csv"],0),
           ("Tier 2","13 covariate modules","each attaches at one merge key",
            ["fta_vn.csv","macro_panel_v2.csv","gravity_vn.csv","glpi.csv","complexity_*.csv","ttbd_vn*.csv","_ntm6/","cbam_products.csv","us_*.csv"],1),
           ("Tier 3","Master panel","158 columns = 16 blocks · 656 MB",
            ["panel_final.csv"],0),
           ("Tier 4","Diagnostic output","results, not explanatory inputs",
            ["km_survival.csv","hazard_baseline.csv","threshold_sensitivity.csv"],2),
           ("Tier 5","Code and documentation","reproducibility and provenance",
            ["scripts/ · 25 files","docs/ · 15 files"],1)],
s11_note="Every file falls into exactly one of three kinds: it defines the unit, attaches to the unit, or is produced from the unit.",
s12_title="Six merge keys — and which fixed effect absorbs each one",
s12_tbl=[["#","Merge key","Modules attaching here","Absorbed by which fixed effect"],
         ["1","spell_id × year","the panel's unit of observation","—"],
         ["2","importer × product_family × year","trade core, historical tariffs","most variation, safest"],
         ["3","importer × year","macro, FTA, gravity, LPI/GLPI, trade remedies, NTM AVE, ECI/COI","dies under importer × year FE"],
         ["4","product_family or HS4 × year","PCI, CBAM scope, US tariff exemptions","dies under product FE"],
         ["5","importer × HS6 × year","NTM6","close to key 2, but weak annual coverage"],
         ["6","year","GEPU, 16 price indices, US tariff 2025, all Viet Nam-side variables","dies completely under year FE"]],
s12_note_h="A consequence of the single-exporter design",
s12_note="Because the exporter is fixed at Viet Nam, every exporter-side variable moves only with the year — a known limitation of the single-exporter design, not a data-building oversight.",
s13_title="Thirteen modules, one sentence each",
s13_tbl=[["Module","Main file","Key","Role","Caveat to state"],
         ["Historical tariffs","panel columns · TRAINS","2","core policy","only 13 reporters name Viet Nam directly"],
         ["FTA","fta_vn.csv · 3,528","3","core policy","knows preference exists, not always the rate"],
         ["US tariffs 2025","6 us_* files","6 + 4","shock extension","four conventions — one must be chosen"],
         ["NTM HS6","_ntm6/ · 126 shards","5","robustness","only 38% of rows surveyed in the right year"],
         ["NTM ad-valorem","ntm_ave_vn.csv · 2,668","3","robustness","a 2017 slice carried across time"],
         ["NTM sector-level","ntm_country/sector/by_type","3","fallback","different concept — do not mix"],
         ["Macro","macro_panel_v2.csv · 3,552","3","core: GDP","extended set for robustness only"],
         ["Green LPI","glpi.csv · 3,552","3","robustness","four constructions, different rankings"],
         ["Gravity","gravity_vn.csv · 2,940","3","core: dist, contig","CEPII stops at 2021"],
         ["Trade remedies","ttbd_vn*.csv","3","robustness","weak observation after 2015"],
         ["Complexity & shocks","complexity_*, shocks_annual","4 / 3 / 6","core: PCI","common shocks die under year FE"],
         ["CBAM","cbam_products.csv · 269","4","extension","not a carbon price yet"],
         ["EPI","epi_indicators_annual.csv","3","input to GLPI","52 indicators, not used directly"]],
s14_title="158 columns, read as blocks rather than variable names",
s14_note="The master panel exists to store everything and keep provenance — not to put 158 variables into one regression. Each model draws one subset.",

s16_note="Survival probability after 1 year 53.1% · 2 years 38.9% · 5 years 25.3% · 10 years 18.9%.",
s17_note="One-year spells are a genuine property of trade-duration data, not noise to be deleted.",
s18_note="Raising the threshold 50-fold moves the one-year share only from 55.3% to 41.9% — this will be handled by stratification or robustness.",
s19_note="Post-2023 cannot yet be read as trend: TRAINS tariffs are carried forward and Comtrade reporting uncertainty is still high.",
s20_note="China and the United States each take over USD 500 billion, yet only about 27% of their spells survive five years or more.",
s21_note="Small relationships dying young is the clearest regularity in the data — and the strongest hazard ratio in the baseline model.",
s22_note="EU-27 gives a more uniform institutional setting, an EVFTA policy shock, and still 148,442 episode-years.",
s23_note="This is a diagnostic showing the pipeline runs. Specification, fixed effects, clustering and timing are not locked — it must not be read as a research result.",

s25_note="High coverage does not mean measured in the right year. Only 38% of NTM HS6 rows are surveyed in their own year, and 30% borrow backwards from a future survey — that must be read as “not yet measured”, not as “low NTM”.",
s26_title="Five limitations to state before being asked",
s26=[("Preferential tariffs are not fully observed",
      "Only 13 reporters file schedules naming Viet Nam. In the panel, 46.3% of episodes have an FTA in force, yet 81.8% of those still carry an MFN-type tariff — so the recorded rate may overstate what is actually applied.",0),
     ("2024–2025 tariffs are carried forward",
      "TRAINS has not published these two years; the panel carries 2023 values forward. Only the US 2025 layer contains genuine new policy variation.",0),
     ("NTM is not an annual series",
      "The researcher file starts in 2010 and countries file on irregular survey schedules. 30% of rows borrow NTM counts backwards from a future survey round.",2),
     ("CBAM is not a carbon price yet",
      "The definitive regime starts 1 Jan 2026, after the panel window. cbam_definitive = 0 across the entire current dataset.",2),
     ("Survival is not automatically causal",
      "A hazard model describes or predicts association. Claiming a policy causes failure requires an identification strategy, treatment timing and a counterfactual.",1)],
s26_rule="A blank is not a zero: US tariff columns are meaningful only for the USA, and CBAM columns only for EU members in the years of their membership.",

s28_title="Four analysis blocks and their true status",
s28_tbl=[["Block","Question","Data used","Status"],
         ["1 · Survival","Which relationships last longer?","spells.csv · Kaplan–Meier","preliminary description done"],
         ["2 · Hazard","What is associated with failure risk?","panel · 5 layers of covariates","pipeline runs, specification not locked"],
         ["3 · Policy shock","Where does the same policy bite differently?","tariffs, FTA/EVFTA, Brexit, NTM, CBAM, US tariffs","data ready, not yet run"],
         ["4 · Portfolio","Given the risk, what should be done?","value × predicted survival probability","not yet defined mathematically"]],
s28_note="The correct phrasing is “the data is ready to test”, not “the research has shown”.",
s29_title="Six decisions we need to lock",
s29=[("01 · Measurement","How is network survivability defined — share of value still alive, minimum portfolio survival probability, or expected loss under a shock?"),
     ("02 · Optimisation","What is the objective function — maximise expected exports, penalise concentration, or a multi-objective utility?"),
     ("03 · Decision rule","Where do the maintain / expand / reduce / enter / exit thresholds sit, and how is the candidate universe built?"),
     ("04 · Econometrics","Main specification: cloglog or Cox, which fixed effects, which clustering, policy at t or t−1?"),
     ("05 · Method","Which GLPI construction becomes the main one, with the other three as sensitivity?"),
     ("06 · Sample","One-year spells: keep in the main model, stratify, or robustness only?")],
s17_t="Distribution of spell durations",
s18_t="Sensitivity to the USD 10,000 threshold",
s19_t="Failure rate by year",
s20_t="A large market is not a durable market",
s21_t="Value and duration move together",
s22_t="Empirical sample scope",
s23_t="Baseline hazard — preliminary diagnostic",
s25_t="Coverage is high; timing is the real problem",
s26_rule_h="How to read the data",
thanks="Thank you",
thanks_sub="Every number in this deck was read directly from analysis/ — none was copied from a description document.",
)
