# -*- coding: utf-8 -*-
C = {}
C["vi"] = dict(
tag="Sinking Relationships",
title="Sinking Relationships",
sub="Độ bền của danh mục xuất khẩu Việt Nam, nhìn từ từng quan hệ mua bán",
kicker="Báo cáo tiến độ dữ liệu",
group=["Nhóm nghiên cứu", "Người trình bày: [điền tên]", "Thành viên: [điền tên]"],
group_note="Dữ liệu: UN Comtrade và WITS · 147 thị trường · 2003–2025",
outline_t="Nội dung",
outline=[("Câu hỏi nghiên cứu","Vì sao tổng kim ngạch là chưa đủ"),
         ("Cách nhìn dữ liệu","Đo tuổi thọ của từng quan hệ mua bán"),
         ("Bản đồ dữ liệu","Sáu lớp thông tin ghép lại thành một bảng"),
         ("Dữ liệu nói gì","Chín phát hiện từ dữ liệu thật"),
         ("Giới hạn","Những gì dữ liệu chưa trả lời được"),
         ("Bước tiếp theo","Sáu điều nhóm cần xin ý kiến")],
sections=[("01","Câu hỏi nghiên cứu","Một danh mục lớn vẫn có thể rất mong manh"),
          ("02","Cách nhìn dữ liệu","Đo tuổi thọ của từng quan hệ mua bán, không chỉ đo tổng"),
          ("03","Bản đồ dữ liệu","Sáu lớp thông tin, ghép lại thành một bảng duy nhất"),
          ("04","Dữ liệu nói gì","Chín phát hiện, tất cả đọc trực tiếp từ dữ liệu"),
          ("05","Giới hạn của dữ liệu","Nói trước những gì chưa trả lời được"),
          ("06","Bước tiếp theo","Nhóm đang ở đâu và cần thầy cho ý kiến gì")],

# --- section 1
s_story_t="Một quan hệ mua bán có thật, kể trong hai mươi năm",
s_story_l="Việt Nam bán một mặt hàng may mặc sang Đức. Nhìn tổng kim ngạch sang Đức thì không thấy gì bất thường.",
s_story_n="Đọc trực tiếp từ dữ liệu nhập khẩu do phía Đức khai báo.",
s_why_t="Điều mà tổng kim ngạch không nói cho ta biết",
s_why_tbl=[["Số liệu thương mại thường dùng","Cách nhóm em nhìn"],
  ["Mỗi dòng là một nước trong một năm","Mỗi dòng là một mặt hàng bán sang một thị trường, trong một năm"],
  ["Trả lời: Việt Nam bán được bao nhiêu","Trả lời: quan hệ mua bán đó giữ được bao lâu"],
  ["Cho thấy danh mục lớn đến đâu","Cho thấy danh mục bền đến đâu"],
  ["Không thấy quan hệ nào đang mất dần","Ước lượng được khả năng một quan hệ sẽ chấm dứt"]],
s_why_q="Kim ngạch cho biết danh mục lớn đến đâu. Nó không cho biết danh mục bền đến đâu.",
s_why_c=("Từ đó đến quyết định","Biết quan hệ nào dễ mất thì mới trả lời được nên giữ, nên mở rộng, hay nên rút khỏi thị trường nào."),

# --- section 2
s_unit_t="Một quan hệ mua bán sống được bao lâu?",
s_unit_l="Cùng một mặt hàng, cùng một thị trường, nhưng hai câu chuyện hoàn toàn khác nhau.",
s_unit_c1=("Khi nào coi là còn bán được","Khi phía nước mua khai nhập từ 10 nghìn USD trở lên trong năm đó. Dưới mức này coi như quan hệ đã ngưng."),
s_unit_c2=("Khi dữ liệu dừng mà vẫn đang bán","Nhóm không coi đó là chấm dứt. Chỉ ghi nhận là quan hệ đã sống được ít nhất chừng đó năm."),
s_files_t="Ba bảng dữ liệu trả lời ba câu hỏi khác nhau",
s_files_l="Cả ba đều dựng từ cùng một nguồn, chỉ khác mức chi tiết.",
s_files_tbl=[["Bảng","Mỗi dòng là gì","Dùng để trả lời","Quy mô"],
  ["Lịch sử quan hệ","một lần bán liên tục từ đầu đến khi ngưng","Quan hệ sống được bao lâu?","228 nghìn dòng"],
  ["Diễn biến từng năm","một quan hệ trong một năm","Năm đó bán được bao nhiêu, còn sống không?","748 nghìn dòng"],
  ["Bảng tổng hợp","một quan hệ trong một năm, kèm mọi thông tin nền","Yếu tố nào đi cùng rủi ro chấm dứt?","748 nghìn dòng · 158 cột"]],
s_files_c=("Vì sao phải gom mã hàng lại","Mã HS đổi theo từng kỳ sửa đổi. Nếu để nguyên, một mặt hàng đổi mã sẽ bị đọc nhầm thành quan hệ cũ chết đi và quan hệ mới sinh ra. Nhóm quy tất cả về một chuẩn gốc, còn 4.621 nhóm hàng ổn định."),
s_size_t="Quy mô dữ liệu nhóm đang có",
s_size_l="Toàn bộ đã dựng xong và kiểm tra trực tiếp trên file, không lấy lại từ tài liệu mô tả.",
s_size_kpi=[("147","thị trường nhập khẩu"),("4.621","nhóm hàng"),("228.175","quan hệ mua bán"),
            ("748 nghìn","quan sát theo năm"),("23","năm dữ liệu")],
s_size_b1=("Nguồn dữ liệu",["Số liệu thương mại của Liên Hợp Quốc và Ngân hàng Thế giới",
  "Biểu thuế nhập khẩu và rào cản phi thuế của UNCTAD",
  "Hiệp định thương mại, khoảng cách địa lý, năng lực hậu cần, độ phức tạp hàng hóa"]),
s_size_b2=("Đã làm và chưa làm",["Thu thập và ghép dữ liệu: đã xong",
  "Thống kê mô tả ban đầu: đã có","Mô hình chính: chưa chốt cách làm",
  "Bài toán tái cơ cấu danh mục: chưa định nghĩa được"]),

# --- section 3
s_map_t="Sáu lớp thông tin, ghép lại thành một bảng",
s_map_l="Mỗi lớp trả lời một câu hỏi khác nhau, và gắn vào bảng chính ở một mức chi tiết khác nhau.",
s_map_tiers=[
 ("Lớp 0","Chọn ai vào nghiên cứu","147 thị trường, kèm lý do loại 46 thị trường khác",0),
 ("Lớp 1","Lịch sử mua bán từng mặt hàng","Nền của toàn bộ phân tích, dựng từ số liệu hải quan",1),
 ("Lớp 2","Mười ba nhóm thông tin nền","Thuế, hiệp định, kinh tế, hậu cần, rào cản, khí hậu",2),
 ("Lớp 3","Bảng tổng hợp cuối cùng","748 nghìn dòng, 158 cột — nguồn duy nhất để chạy mô hình",3),
 ("Lớp 4","Kết quả phân tích ban đầu","Đường sống sót, mô hình rủi ro thử nghiệm",2),
 ("Lớp 5","Mã nguồn và tài liệu","25 chương trình, 16 tài liệu — để dựng lại được từ đầu",0)],
s_map_n="Mọi bảng trong bộ dữ liệu đều thuộc một trong ba loại: định nghĩa mẫu, gắn thông tin vào quan hệ, hoặc là kết quả sinh ra từ quan hệ.",
s_lvl_t="Mỗi lớp thông tin mô tả một mức khác nhau",
s_lvl_l="Đây là điều quyết định thông tin nào còn dùng được khi mô hình kiểm soát các yếu tố cố định.",
s_lvl_tbl=[["Thông tin thay đổi theo","Gồm những gì","Lưu ý khi đưa vào mô hình"],
 ["Từng quan hệ, từng năm","Giá trị bán được, số năm đã tồn tại","Đây là đơn vị phân tích"],
 ["Từng mặt hàng ở từng thị trường, từng năm","Thuế nhập khẩu áp cho hàng Việt Nam","Biến thiên nhiều nhất, dùng được rộng rãi"],
 ["Từng thị trường, từng năm","Kinh tế nước mua, hiệp định thương mại, hậu cần, khoảng cách, phòng vệ thương mại","Không tách được nếu mô hình kiểm soát theo từng thị trường-năm"],
 ["Từng mặt hàng","Độ phức tạp hàng hóa, phạm vi cơ chế carbon của EU","Không tách được nếu mô hình kiểm soát theo mặt hàng"],
 ["Chỉ theo năm","Biến động kinh tế toàn cầu, giá hàng hóa, thuế Mỹ 2025, mọi yếu tố phía Việt Nam","Không tách được nếu mô hình kiểm soát theo năm"]],
s_lvl_c=("Hệ quả của việc chỉ nghiên cứu một nước xuất khẩu","Vì Việt Nam là nước xuất khẩu duy nhất, mọi yếu tố phía Việt Nam chỉ thay đổi theo năm. Đây là giới hạn đã biết của thiết kế, nhóm sẽ nói rõ khi trình bày kết quả."),
s_blk_t="Bảng tổng hợp gồm những nhóm thông tin nào",
s_blk_l="158 cột, nhưng chỉ có bốn nhóm lớn. Mỗi mô hình chỉ dùng một phần, không dùng tất cả.",
s_blk_n="Bảng tổng hợp được thiết kế để lưu đủ và truy được nguồn, không phải để đưa tất cả vào cùng một mô hình.",

# --- section 4
s_flows_t="Danh mục xuất khẩu lớn gấp mười lần trong hai mươi năm",
s_flows_l="Nhưng phía dưới con số đó là dòng quan hệ mới mở và quan hệ chấm dứt gần như tương đương nhau mỗi năm.",
s_flows_n="Dừng ở 2023 vì số liệu 2024–2025 chưa đủ nước báo cáo để đọc như xu hướng.",
s_km_t="Hơn một nửa quan hệ không sống quá năm đầu tiên",
s_km_l="Đây là đặc điểm chung của thương mại quốc tế, không riêng Việt Nam.",
s_km_n="Nhóm có hiệp định thương mại sống lâu hơn, nhưng đây mới là thống kê mô tả — hai nhóm còn khác nhau về quy mô thị trường và cơ cấu hàng hóa.",
s_dur_t="Một nửa số quan hệ chỉ tồn tại đúng một năm",
s_dur_l="Nhóm đã thử nâng ngưỡng lên gấp năm mươi lần; tỷ lệ này chỉ giảm từ 55% xuống 42%.",
s_dur_n="Vì vậy nhóm sẽ xử lý bằng cách tách nhóm hoặc kiểm tra độ vững, không xóa các quan hệ ngắn.",
s_sz_t="Quan hệ càng nhỏ càng dễ mất",
s_sz_l="Chia toàn bộ quan hệ thành bốn nhóm theo giá trị đơn hàng năm đầu tiên.",
s_sz_n="Nhóm đơn hàng lớn nhất có khả năng sống đến năm thứ năm gấp đôi nhóm nhỏ nhất.",
s_sec_t="Ngành nào bền hơn, và ngành nào mang lại nhiều tiền hơn",
s_sec_l="Hai câu hỏi này cho hai câu trả lời khác nhau.",
s_sec_n="Máy móc và điện tử chiếm phần lớn giá trị xuất khẩu nhưng độ bền chỉ ở mức trung bình.",
s_map2_t="Giá trị lớn không đi cùng độ bền cao",
s_map2_l="Mỗi bong bóng là một ngành hàng. Trục ngang là tiền, trục dọc là độ bền.",
s_map2_n="Góc phải dưới là vùng đáng lo: đóng góp nhiều giá trị nhưng quan hệ dễ đứt gãy.",
s_mk_t="Thị trường lớn cũng không phải thị trường bền",
s_mk_l="Mười hai thị trường lớn nhất của Việt Nam, xếp theo giá trị và theo độ bền.",
s_mk_n="Trung Quốc và Hoa Kỳ mỗi nước trên 500 tỷ USD, nhưng chỉ khoảng 27% quan hệ trụ được năm năm.",
s_cc_t="Danh mục ngày càng dồn vào ít thị trường và ít mặt hàng",
s_cc_l="Phần của năm thị trường lớn nhất và mười mặt hàng lớn nhất trong tổng giá trị xuất khẩu.",
s_cc_n="Mười mặt hàng lớn nhất tăng từ 17% lên 57% tổng giá trị chỉ trong hai mươi năm.",
s_hz_t="Yếu tố nào đi cùng rủi ro chấm dứt",
s_hz_l="Kết quả thử nghiệm ban đầu. Đọc là mối liên hệ, chưa phải quan hệ nhân quả.",
s_hz_n="Nhóm chưa chốt cách xây mô hình, nên chưa dùng các con số này làm kết luận nghiên cứu.",

# --- section 5
s_q_t="Dữ liệu đầy đủ đến đâu",
s_q_l="Độ phủ cao không có nghĩa là đo đúng thời điểm. Đây mới là vấn đề thật.",
s_q_n="Rào cản phi thuế chỉ có 38% số dòng được khảo sát đúng năm đó — phần còn lại phải mượn từ kỳ khảo sát khác.",
s_lim_t="Năm điều nhóm cần nói trước",
s_lim=[("Thuế ưu đãi chưa đo được đầy đủ",
   "Gần một nửa số quan sát có hiệp định thương mại đang hiệu lực, nhưng phần lớn vẫn ghi mức thuế thông thường. Mức thuế thực tế doanh nghiệp phải chịu có thể thấp hơn con số trong dữ liệu.",0),
  ("Hai năm gần nhất chưa có biểu thuế mới",
   "Nguồn quốc tế chưa công bố cho 2024 và 2025, nên dữ liệu đang giữ nguyên mức của 2023. Nhóm tách riêng hai năm này thay vì trộn vào phân tích chính.",0),
  ("Rào cản phi thuế không có đủ hằng năm",
   "Các nước chỉ khảo sát theo đợt, không đều. Số 0 trong dữ liệu nhiều khi có nghĩa là chưa đo được, chứ không phải là không có rào cản.",1),
  ("Cơ chế carbon của EU chưa thành chi phí",
   "Giai đoạn bắt buộc chỉ bắt đầu từ 2026, sau khoảng thời gian dữ liệu. Hiện mới ghi nhận mặt hàng nào thuộc phạm vi phải báo cáo.",1),
  ("Đo được liên hệ, chưa đo được nguyên nhân",
   "Muốn nói một chính sách gây ra đứt gãy thì cần thiết kế nhận dạng riêng, chứ không thể kết luận từ mô hình mô tả.",2)],
s_lim_c=("Một quy tắc đọc dữ liệu","Ô trống không có nghĩa là số 0. Cột thuế Mỹ chỉ áp dụng cho thị trường Hoa Kỳ, cột cơ chế carbon chỉ áp dụng cho các nước EU."),

# --- section 6
s_sc_t="Phạm vi phân tích nhóm chọn",
s_sc_l="Liên minh châu Âu là mẫu chính; toàn cầu dùng để kiểm tra kết luận có còn đúng không.",
s_sc_n="EU cho bối cảnh chính sách thống nhất hơn và có hiệp định EVFTA làm mốc thay đổi rõ ràng.",
s_st_t="Nhóm đang ở đâu",
s_st_tbl=[["Phần việc","Câu hỏi cần trả lời","Trạng thái"],
 ["Mô tả tuổi thọ quan hệ","Quan hệ nào sống lâu hơn?","Đã có kết quả ban đầu"],
 ["Mô hình rủi ro","Yếu tố nào đi cùng rủi ro chấm dứt?","Chạy được, chưa chốt cách làm"],
 ["Tác động chính sách","Cùng một thay đổi, ai chịu ảnh hưởng nặng hơn?","Dữ liệu sẵn, chưa chạy"],
 ["Tái cơ cấu danh mục","Biết rủi ro rồi thì nên làm gì?","Chưa định nghĩa được"]],
s_st_c=("Cách nói đúng khi trình bày","Dữ liệu đã sẵn sàng để kiểm định, chứ chưa phải nghiên cứu đã chứng minh."),
s_dec_t="Sáu điều nhóm xin thầy cho ý kiến",
s_dec=[("Đo độ bền của cả danh mục thế nào?","Theo phần giá trị còn giữ được, theo khả năng sống thấp nhất, hay theo mức thiệt hại kỳ vọng khi có cú sốc?"),
 ("Mục tiêu tối ưu là gì?","Tối đa giá trị xuất khẩu kỳ vọng, hay có tính cả việc phạt sự tập trung quá mức?"),
 ("Đặt ngưỡng hành động ở đâu?","Đến mức nào thì nên giữ, mở rộng, thu hẹp hay rút khỏi một quan hệ?"),
 ("Chọn cách xây mô hình nào?","Dùng dạng mô hình nào, kiểm soát những yếu tố cố định nào, và chính sách tính ở năm nào?"),
 ("Chọn cách đo hậu cần xanh nào?","Nhóm có bốn cách xây, cho thứ hạng các nước khác nhau đáng kể."),
 ("Xử lý quan hệ một năm ra sao?","Giữ trong mô hình chính, tách riêng, hay chỉ dùng để kiểm tra độ vững?")],
thanks="Xin cảm ơn thầy",
thanks_sub="Mọi con số trong bài đều đọc trực tiếp từ dữ liệu đã dựng.",
)

C["en"] = dict(
tag="Sinking Relationships",
title="Sinking Relationships",
sub="How durable Viet Nam's export portfolio is, seen one trading relationship at a time",
kicker="Data Progress Report",
group=["Research group", "Presenter: [your name]", "Members: [names]"],
group_note="Data: UN Comtrade and WITS · 147 markets · 2003–2025",
outline_t="Contents",
outline=[("The research question","Why total export value is not enough"),
         ("How we look at the data","Measuring how long each relationship lasts"),
         ("The data map","Six layers of information joined into one table"),
         ("What the data shows","Nine findings, read straight from the data"),
         ("Limitations","What the data cannot answer yet"),
         ("Next steps","Six questions we need your guidance on")],
sections=[("01","The research question","A large portfolio can still be a fragile one"),
          ("02","How we look at the data","Measuring the lifetime of each relationship, not just the total"),
          ("03","The data map","Six layers of information, joined into a single table"),
          ("04","What the data shows","Nine findings, all read directly from the data"),
          ("05","Limitations of the data","Stating up front what cannot be answered yet"),
          ("06","Next steps","Where we stand and what we need your guidance on")],

s_story_t="One real trading relationship, told over twenty years",
s_story_l="Viet Nam sold an apparel line to Germany. Looking at total exports to Germany, nothing seems wrong.",
s_story_n="Read directly from the import figures reported by the German side.",
s_why_t="What total export value does not tell us",
s_why_tbl=[["Standard trade statistics","How we look at it"],
  ["One row is one country in one year","One row is one product sold to one market, in one year"],
  ["Answers: how much Viet Nam sold","Answers: how long that trading relationship held"],
  ["Shows how large the portfolio is","Shows how durable the portfolio is"],
  ["Cannot see a relationship fading","Can estimate the chance a relationship will end"]],
s_why_q="Export value tells us how large the portfolio is. It does not tell us how durable it is.",
s_why_c=("From there to a decision","Knowing which relationships are fragile is what makes it possible to say which markets to keep, expand, or step away from."),

s_unit_t="How long does a trading relationship last?",
s_unit_l="The same product, the same market, and two completely different stories.",
s_unit_c1=("When we count it as still selling","When the buying country reports at least USD 10,000 of imports that year. Below that, we treat the relationship as paused."),
s_unit_c2=("Still selling when the data stops","We do not count that as an ending. We only record that the relationship lasted at least that long."),
s_files_t="Three tables answering three different questions",
s_files_l="All three come from the same source; they differ only in level of detail.",
s_files_tbl=[["Table","What one row is","Used to answer","Size"],
  ["Relationship history","one continuous run of selling, start to stop","How long did the relationship last?","228 thousand rows"],
  ["Year by year","one relationship in one year","How much sold that year, and was it still alive?","748 thousand rows"],
  ["Combined table","one relationship in one year, with all background information","What is associated with the risk of ending?","748 thousand rows · 158 columns"]],
s_files_c=("Why product codes had to be grouped","HS codes change at every revision. Left as they are, a product changing code would be read as an old relationship dying and a new one being born. We mapped everything back to one base standard, leaving 4,621 stable product groups."),
s_size_t="The size of the dataset we now hold",
s_size_l="Everything has been built and verified against the files themselves, not copied from a description document.",
s_size_kpi=[("147","importing markets"),("4,621","product groups"),("228,175","trading relationships"),
            ("748 thousand","yearly observations"),("23","years of data")],
s_size_b1=("Where the data comes from",["Trade statistics from the United Nations and the World Bank",
  "Import tariffs and non-tariff barriers from UNCTAD",
  "Trade agreements, distance, logistics capacity, product complexity"]),
s_size_b2=("Done and not yet done",["Collection and joining: complete",
  "Initial descriptive statistics: available","Main model: approach not yet fixed",
  "Portfolio restructuring problem: not yet defined"]),

s_map_t="Six layers of information, joined into one table",
s_map_l="Each layer answers a different question, and attaches to the main table at a different level of detail.",
s_map_tiers=[
 ("Layer 0","Choosing who enters the study","147 markets, with reasons for excluding 46 others",0),
 ("Layer 1","The selling history of each product","The foundation of the whole analysis, built from customs figures",1),
 ("Layer 2","Thirteen groups of background information","Tariffs, agreements, economy, logistics, barriers, climate",2),
 ("Layer 3","The final combined table","748 thousand rows, 158 columns — the single source for every model",3),
 ("Layer 4","Initial analysis results","Survival curves and a trial risk model",2),
 ("Layer 5","Code and documentation","25 programs, 16 documents — so it can be rebuilt from scratch",0)],
s_map_n="Every table in the dataset is one of three things: it defines the sample, it attaches information to a relationship, or it is a result produced from one.",
s_lvl_t="Each layer describes a different level",
s_lvl_l="This is what decides which information survives once the model controls for fixed factors.",
s_lvl_tbl=[["Information varies by","What it covers","What to watch when modelling"],
 ["Each relationship, each year","Value sold, years already survived","This is the unit of analysis"],
 ["Each product in each market, each year","Import tariffs applied to Vietnamese goods","Varies the most, usable throughout"],
 ["Each market, each year","Buyer economy, trade agreements, logistics, distance, trade defence","Cannot be separated if the model controls for each market-year"],
 ["Each product","Product complexity, scope of the EU carbon mechanism","Cannot be separated if the model controls for product"],
 ["The year only","Global economic conditions, commodity prices, US tariffs 2025, everything on the Viet Nam side","Cannot be separated if the model controls for year"]],
s_lvl_c=("A consequence of studying a single exporter","Because Viet Nam is the only exporter, everything on the Viet Nam side varies only by year. This is a known limitation of the design, and we will state it when presenting results."),
s_blk_t="What the combined table contains",
s_blk_l="158 columns, but only four broad groups. Each model uses a part of it, never all of it.",
s_blk_n="The combined table exists to hold everything and keep provenance — not to put all of it into one model.",

s_flows_t="The export portfolio grew tenfold in twenty years",
s_flows_l="Underneath that number, relationships opening and relationships ending run at almost the same rate every year.",
s_flows_n="Stopping at 2023 because too few countries have reported 2024–2025 for it to be read as a trend.",
s_km_t="More than half of relationships do not survive their first year",
s_km_l="This is a general feature of international trade, not something specific to Viet Nam.",
s_km_n="Relationships covered by a trade agreement last longer, but this is descriptive only — the two groups also differ in market size and product mix.",
s_dur_t="Half of all relationships last exactly one year",
s_dur_l="We raised the threshold fifty-fold as a test; the share only fell from 55% to 42%.",
s_dur_n="So we will handle it by separating groups or testing robustness, not by deleting short relationships.",
s_sz_t="The smaller the relationship, the more likely it is lost",
s_sz_l="All relationships split into four groups by the value of the first year's orders.",
s_sz_n="The largest group is twice as likely to reach year five as the smallest.",
s_sec_t="Which sectors last longer, and which bring in more money",
s_sec_l="These two questions give two different answers.",
s_sec_n="Machinery and electronics account for most of the export value, yet their durability is only average.",
s_map2_t="High value does not come with high durability",
s_map2_l="Each bubble is a sector. Horizontal is money, vertical is durability.",
s_map2_n="The lower right is the area of concern: large contribution to value, but fragile relationships.",
s_mk_t="Large markets are not durable markets either",
s_mk_l="Viet Nam's twelve largest markets, ranked by value and by durability.",
s_mk_n="China and the United States each take over USD 500 billion, yet only about 27% of relationships reach five years.",
s_cc_t="The portfolio is concentrating into fewer markets and fewer products",
s_cc_l="Share of the top five markets and the top ten products in total export value.",
s_cc_n="The ten largest products went from 17% to 57% of total value in just twenty years.",
s_hz_t="What is associated with the risk of ending",
s_hz_l="A first trial result. Read it as association, not yet as cause.",
s_hz_n="We have not fixed the modelling approach, so these numbers are not used as research conclusions.",

s_q_t="How complete is the data",
s_q_l="High coverage does not mean measured at the right time. That is the real problem.",
s_q_n="Only 38% of non-tariff barrier rows were surveyed in their own year — the rest borrow from another survey round.",
s_lim_t="Five things we need to say up front",
s_lim=[("Preferential tariffs are not fully observed",
   "Almost half the observations have a trade agreement in force, yet most still record the standard tariff. The rate firms actually face may be lower than what the data shows.",0),
  ("No new tariff schedule for the last two years",
   "The international source has not published 2024 or 2025, so the data carries the 2023 rate forward. We keep those two years separate from the main analysis.",0),
  ("Non-tariff barriers are not available every year",
   "Countries survey in irregular rounds. A zero in the data often means not yet measured, rather than no barrier.",1),
  ("The EU carbon mechanism is not yet a cost",
   "The binding phase only starts in 2026, after our data window. For now we only record which products fall within the reporting scope.",1),
  ("We measure association, not cause",
   "Claiming that a policy causes a relationship to end requires a dedicated identification design; it cannot be concluded from a descriptive model.",2)],
s_lim_c=("One rule for reading the data","A blank is not a zero. The US tariff columns apply only to the United States, and the carbon mechanism columns only to EU countries."),

s_sc_t="The analytical scope we chose",
s_sc_l="The European Union is the main sample; the global panel checks whether the conclusions still hold.",
s_sc_n="The EU offers a more uniform policy setting and the EVFTA agreement as a clear turning point.",
s_st_t="Where we stand",
s_st_tbl=[["Work","Question to answer","Status"],
 ["Describing relationship lifetimes","Which relationships last longer?","First results available"],
 ["Risk model","What is associated with the risk of ending?","Runs, approach not yet fixed"],
 ["Policy impact","For the same change, who is hit harder?","Data ready, not yet run"],
 ["Portfolio restructuring","Given the risk, what should be done?","Not yet defined"]],
s_st_c=("The right way to phrase it","The data is ready to be tested, not the research has been proven."),
s_dec_t="Six questions we need your guidance on",
s_dec=[("How should portfolio durability be measured?","By the share of value retained, by the lowest survival chance, or by expected loss under a shock?"),
 ("What is the objective?","Maximise expected export value, or also penalise excessive concentration?"),
 ("Where do the action thresholds sit?","At what point should a relationship be kept, expanded, reduced, or exited?"),
 ("Which modelling approach?","Which model form, which fixed factors to control for, and in which year is policy measured?"),
 ("Which green logistics measure?","We have four constructions, and they rank countries quite differently."),
 ("How to treat one-year relationships?","Keep them in the main model, separate them, or use them only for robustness?")],
thanks="Thank you",
thanks_sub="Every number in this deck was read directly from the dataset we built.",
)
