# -*- coding: utf-8 -*-
LABELS = {
"vi": {
 "year":"Năm", "musd":"Triệu USD", "dur_years":"Thời gian tồn tại (năm)",
 "surv_pct":"Xác suất còn sống", "n_spells":"Số spell", "threshold":"Ngưỡng (USD)",
 "peak":"Đỉnh {v} triệu USD", "start":"Năm đầu: 19 nghìn USD", "death":"Chết sau 2021",
 "gone":"quan hệ không còn", 
 "f1_title":"Một quan hệ có thật: Đức × H0_620291 — lớn dần rồi chết",
 "r_291":"Đức × H0_620291", "r_429":"Đức × H0_620429",
 "one_spell":"một spell duy nhất · 17 năm", "five_spells":"năm spell rời rạc · chết đi sống lại",
 "alive":"spell đang sống", "event1":"event = 1 (đứt gãy)", "rcens":"right-censored",
 "censored":"còn sống khi hết dữ liệu",
 "f2_title":"Đơn vị quan sát: quan hệ → spell → episode-năm",
 "km_all":"Toàn mẫu (228.175 spell)", "km_fta":"Có FTA", "km_nofta":"Không FTA",
 "f3_title":"Kaplan–Meier: hơn một nửa quan hệ không sống quá năm đầu",
 "f3_note":"Chênh lệch FTA là thống kê mô tả, chưa xử lý selection — chưa phải bằng chứng nhân quả.",
 "f4_title":"Phân phối thời gian tồn tại của spell",
 "f4_note":"52,7% spell chỉ dài\nđúng một năm",
 "f5_title":"Độ nhạy theo ngưỡng: spell một năm không biến mất",
 "f5_a":"Số spell theo ngưỡng", "f5_b":"Tỷ lệ spell một năm và giá trị giữ lại",
 "pct1y":"% spell một năm", "pctval":"% giá trị thương mại giữ lại", "current":"đang dùng",
 "f6_title":"158 cột của panel_final.csv, nhóm thành 16 khối",
 "b_id":"Định danh + survival", "b_trade":"Trade + cấu trúc", "b_tar":"Thuế", "b_mx":"Vĩ mô VN",
 "b_mm":"Vĩ mô importer", "b_lpi":"LPI", "b_glpi":"GLPI", "b_fta":"FTA",
 "b_ttb":"Phòng vệ TM", "b_grav":"Gravity + thể chế", "b_us":"Thuế Mỹ 2025", "b_ave":"NTM AVE",
 "b_shock":"Sốc chung", "b_pci":"Độ phức tạp", "b_cbam":"CBAM", "b_ntms":"NTM ngành",
 "b_ntm6":"NTM HS6×năm",
 "g_core":"Lõi", "g_pol":"Chính sách", "g_ctx":"Bối cảnh", "g_ntm":"NTM", "cols":"cột",
 "f7_title":"Phạm vi mẫu: EU-27 là mẫu chính, toàn cầu để kiểm tra khái quát",
 "s_eu":"EU-27\n2003–2023", "s_uk":"UK\n2003–2023", "s_gl":"Toàn cầu\n147 thị trường",
 "k_ep":"Episode-năm", "k_sp":"Spell", "k_ev":"Event (đứt gãy)", "k_fa":"Nhóm sản phẩm",
 "f8_title":"Chất lượng dữ liệu: độ phủ cao, nhưng thời điểm đo mới là vấn đề",
 "f8_a":"Độ phủ theo module (% dòng panel có giá trị)",
 "f8_b":"Biến chính sách được đo đúng năm hay mượn từ năm khác?",
 "q_tar":"Thuế TRAINS", "q_ntm":"NTM HS6", "q_grav":"Gravity CEPII",
 "q_exact":"đúng năm", "q_past":"mượn từ quá khứ", "q_future":"mượn từ tương lai",
 "cov_map":{"Trade / survival":"Trade / survival","RCA":"RCA","Tariff":"Thuế lịch sử","FTA":"FTA",
   "Macro GDP":"Vĩ mô (GDP)","Gravity":"Gravity","LPI":"LPI","Green LPI":"Green LPI","PCI":"PCI",
   "NTM HS6":"NTM HS6","NTM AVE":"NTM AVE","Trade remedies":"Phòng vệ thương mại",
   "CBAM scope":"CBAM (chỉ EU)","US tariff 2025":"Thuế Mỹ 2025 (chỉ USA)"},
 "f9_title":"Thị trường lớn không phải thị trường bền",
 "f9_x":"Tổng giá trị nhập khẩu từ Việt Nam, 2003–2025 (tỷ USD, thang log)",
 "f9_y":"% spell sống được từ 5 năm trở lên",
 "f9_note":"Kích thước điểm = số spell · 12 thị trường lớn nhất",
 "f10_title":"Hazard baseline (cloglog) — chẩn đoán sơ bộ",
 "hr":"Hazard ratio (khoảng tin cậy 95%)",
 "haz_hi":"HR > 1: rủi ro đứt gãy cao hơn", "haz_lo":"HR < 1: rủi ro đứt gãy thấp hơn",
 "haz_map":{"log_tariff_1p":"log(1 + thuế)","fta_in_force":"FTA đang hiệu lực",
   "log_gdp":"log GDP importer","log_dist":"log khoảng cách","pci":"PCI (độ phức tạp SP)",
   "log_rca_1p":"log(1 + RCA)","log_value":"log giá trị xuất khẩu",
   "partner_share_pct":"Tỷ trọng đối tác (%)"},
 "f11_title":"Tỷ lệ đứt gãy theo năm: giảm dần, nhưng nhạy với cú sốc",
 "ev_rate":"% episode kết thúc bằng đứt gãy", "gfc":"Khủng hoảng 2008", "covid":"COVID-19",
 "f11_note":"2024–2025 chưa đọc được như xu hướng: độ bất định về báo cáo Comtrade còn cao.",
 "f12_title":"Quan hệ giá trị nhỏ chết sớm — mẫu EU-27, spell đã chấm dứt",
 "median_val":"Giá trị trung vị", "log_val":"Giá trị trung bình mỗi năm (USD)",
},
"en": {
 "year":"Year", "musd":"USD million", "dur_years":"Spell duration (years)",
 "surv_pct":"Survival probability", "n_spells":"Number of spells", "threshold":"Threshold (USD)",
 "peak":"Peak USD {v}M", "start":"First year: USD 19K", "death":"Dies after 2021",
 "gone":"relationship gone",
 "f1_title":"One real relationship: Germany × H0_620291 — it grew, then died",
 "r_291":"Germany × H0_620291", "r_429":"Germany × H0_620429",
 "one_spell":"a single spell · 17 years", "five_spells":"five separate spells · dies and returns",
 "alive":"spell alive", "event1":"event = 1 (failure)", "rcens":"right-censored",
 "censored":"still alive at end of data",
 "f2_title":"The unit of observation: relationship → spell → episode-year",
 "km_all":"Full sample (228,175 spells)", "km_fta":"With FTA", "km_nofta":"No FTA",
 "f3_title":"Kaplan–Meier: more than half of relationships do not survive year one",
 "f3_note":"The FTA gap is descriptive only — selection and confounders are not addressed. Not causal evidence.",
 "f4_title":"Distribution of spell durations",
 "f4_note":"52.7% of spells last\nexactly one year",
 "f5_title":"Threshold sensitivity: one-year spells do not go away",
 "f5_a":"Spells retained by threshold", "f5_b":"One-year share and trade value retained",
 "pct1y":"% one-year spells", "pctval":"% of trade value retained", "current":"in use",
 "f6_title":"The 158 columns of panel_final.csv, grouped into 16 blocks",
 "b_id":"ID + survival", "b_trade":"Trade + structure", "b_tar":"Tariff", "b_mx":"Macro VN",
 "b_mm":"Macro importer", "b_lpi":"LPI", "b_glpi":"GLPI", "b_fta":"FTA",
 "b_ttb":"Trade remedies", "b_grav":"Gravity + institutions", "b_us":"US tariff 2025",
 "b_ave":"NTM AVE", "b_shock":"Common shocks", "b_pci":"Complexity", "b_cbam":"CBAM",
 "b_ntms":"NTM sector", "b_ntm6":"NTM HS6×year",
 "g_core":"Core", "g_pol":"Policy", "g_ctx":"Context", "g_ntm":"NTM", "cols":"columns",
 "f7_title":"Sample scope: EU-27 is the main sample, global is the generalisability check",
 "s_eu":"EU-27\n2003–2023", "s_uk":"UK\n2003–2023", "s_gl":"Global\n147 markets",
 "k_ep":"Episode-years", "k_sp":"Spells", "k_ev":"Events (failures)", "k_fa":"Product families",
 "f8_title":"Data quality: coverage is high — timing is the real problem",
 "f8_a":"Module coverage (% of panel rows with a value)",
 "f8_b":"Are policy variables measured in the right year?",
 "q_tar":"TRAINS tariff", "q_ntm":"NTM HS6", "q_grav":"CEPII gravity",
 "q_exact":"exact year", "q_past":"borrowed from past", "q_future":"borrowed from future",
 "cov_map":{"CBAM scope":"CBAM (EU only)","US tariff 2025":"US tariff 2025 (USA only)"},
 "f9_title":"A large market is not a durable market",
 "f9_x":"Total imports from Viet Nam, 2003–2025 (USD bn, log scale)",
 "f9_y":"% of spells surviving 5 years or more",
 "f9_note":"Bubble size = number of spells · 12 largest markets",
 "f10_title":"Baseline hazard (cloglog) — preliminary diagnostic",
 "hr":"Hazard ratio (95% confidence interval)",
 "haz_hi":"HR > 1: higher failure risk", "haz_lo":"HR < 1: lower failure risk",
 "haz_map":{"log_tariff_1p":"log(1 + tariff)","fta_in_force":"FTA in force",
   "log_gdp":"log importer GDP","log_dist":"log distance","pci":"PCI (product complexity)",
   "log_rca_1p":"log(1 + RCA)","log_value":"log export value",
   "partner_share_pct":"Partner share (%)"},
 "f11_title":"Failure rate by year: declining, but sensitive to shocks",
 "ev_rate":"% of episodes ending in failure", "gfc":"2008 crisis", "covid":"COVID-19",
 "f11_note":"2024–2025 cannot yet be read as trend: Comtrade reporting uncertainty is still high.",
 "f12_title":"Small relationships die young — EU-27 sample, completed spells",
 "median_val":"Median value", "log_val":"Mean annual value (USD)",
},
}
# English coverage labels default to their original English keys
for k in ["Trade / survival","RCA","Tariff","FTA","Macro GDP","Gravity","LPI","Green LPI",
          "PCI","NTM HS6","NTM AVE","Trade remedies"]:
    LABELS["en"]["cov_map"].setdefault(k, k)
