# -*- coding: utf-8 -*-
SEC_VI = dict(machinery="Máy móc & điện tử", textile="Dệt may", metal="Kim loại cơ bản",
  plastic="Nhựa & cao su", precision="Thiết bị chính xác", wood="Gỗ & giấy",
  veg="Nông sản thực vật", chem="Hóa chất", footwear="Giày dép & mũ",
  food="Thực phẩm chế biến", stone="Đá, gốm, thủy tinh", transport="Phương tiện vận tải",
  leather="Da & lông", animal="Sản phẩm động vật", mineral="Khoáng sản",
  misc="Hàng hóa khác", fats="Dầu mỡ")
SEC_EN = dict(machinery="Machinery & electronics", textile="Textiles & apparel",
  metal="Base metals", plastic="Plastics & rubber", precision="Precision instruments",
  wood="Wood & paper", veg="Vegetable products", chem="Chemicals",
  footwear="Footwear & headgear", food="Processed food", stone="Stone, ceramics, glass",
  transport="Transport equipment", leather="Hides & leather", animal="Animal products",
  mineral="Mineral products", misc="Miscellaneous goods", fats="Fats & oils")

BLOCKS_VI = ["Nhận dạng quan hệ","Quy mô & vị thế","Thuế nhập khẩu","Kinh tế nước mua",
  "Năng lực hậu cần","Hậu cần xanh","Khoảng cách & thể chế","Hiệp định thương mại",
  "Phòng vệ thương mại","Biến động toàn cầu","Thuế Mỹ 2025","Rào cản quy đổi",
  "Độ phức tạp hàng hóa","Cơ chế carbon EU",
  "Rào cản theo ngành","Rào cản chi tiết"]
BLOCKS_EN = ["Relationship identity","Size & position","Import tariffs","Buyer economy",
  "Logistics capacity","Green logistics","Distance & institutions","Trade agreements",
  "Trade defence","Global conditions","US tariffs 2025","Barriers in tariff terms",
  "Product complexity","EU carbon mechanism",
  "Barriers by sector","Barriers in detail"]

HAZ_VI = {"log_value":"Quy mô đơn hàng lớn hơn","log_rca_1p":"Lợi thế so sánh cao hơn",
  "fta_in_force":"Có hiệp định thương mại","log_gdp":"Nước mua giàu hơn",
  "log_dist":"Khoảng cách xa hơn","pci":"Hàng hóa phức tạp hơn",
  "log_tariff_1p":"Thuế nhập khẩu cao hơn","partner_share_pct":"Đối tác quan trọng hơn"}
HAZ_EN = {"log_value":"Larger order size","log_rca_1p":"Stronger comparative advantage",
  "fta_in_force":"Trade agreement in force","log_gdp":"Richer buyer economy",
  "log_dist":"Greater distance","pci":"More complex product",
  "log_tariff_1p":"Higher import tariff","partner_share_pct":"More important partner"}

COV_VI = {"Trade / survival":"Giá trị & thời gian tồn tại","RCA":"RCA",
  "Tariff":"Thuế nhập khẩu","FTA":"Hiệp định thương mại","Macro GDP":"Kinh tế nước mua",
  "Gravity":"Khoảng cách & thể chế","LPI":"Năng lực hậu cần","Green LPI":"Hậu cần xanh",
  "PCI":"Độ phức tạp hàng hóa","NTM HS6":"Rào cản phi thuế","NTM AVE":"Rào cản quy đổi",
  "Trade remedies":"Phòng vệ thương mại","CBAM scope":"Cơ chế carbon EU (chỉ EU)",
  "US tariff 2025":"Thuế Mỹ 2025 (chỉ Hoa Kỳ)"}
COV_EN = {"Trade / survival":"Value & duration","RCA":"RCA","Tariff":"Import tariffs",
  "FTA":"Trade agreements","Macro GDP":"Buyer economy","Gravity":"Distance & institutions",
  "LPI":"Logistics capacity","Green LPI":"Green logistics","PCI":"Product complexity",
  "NTM HS6":"Non-tariff barriers","NTM AVE":"Barriers in tariff terms",
  "Trade remedies":"Trade defence","CBAM scope":"EU carbon mechanism (EU only)",
  "US tariff 2025":"US tariffs 2025 (USA only)"}

LAB = {
"vi": dict(sec=SEC_VI, blocks=BLOCKS_VI, haz=HAZ_VI, cov=COV_VI,
  s_y="Triệu USD mỗi năm", s_peak="Đỉnh 1,92 triệu USD", s_first="Năm đầu: 19 nghìn USD",
  s_end="Đơn hàng cuối cùng", s_gone="không còn đơn hàng nào",
  t_r1="Đức · một mặt hàng may mặc", t_r2="Đức · một mặt hàng may mặc khác",
  t_cens="vẫn đang bán khi dữ liệu dừng",
  t_n1="bán liên tục 17 năm rồi dừng hẳn", t_n2="bán rồi ngưng, ngưng rồi bán lại — năm lần",
  fl_y1="Số quan hệ đang hoạt động", fl_y2="Mỗi năm",
  fl_new="quan hệ mới mở", fl_exit="quan hệ chấm dứt",
  km_all="Toàn bộ", km_fta="Có hiệp định", km_no="Không hiệp định",
  km_x="Số năm quan hệ đã tồn tại", km_y="Tỷ lệ còn bán được",
  sz_q1="Nhóm nhỏ nhất", sz_q2="Nhóm nhỏ", sz_q3="Nhóm lớn", sz_q4="Nhóm lớn nhất",
  se_x1="Tỷ lệ quan hệ sống được từ 5 năm trở lên",
  se_x2="Tổng giá trị xuất khẩu 2003–2025 (tỷ USD)",
  mp_x="Tổng giá trị xuất khẩu (tỷ USD, thang log)",
  mp_y="Tỷ lệ quan hệ sống từ 5 năm trở lên (%)",
  mp_note="Kích thước bong bóng = tổng giá trị · màu cam = giá trị lớn nhưng kém bền",
  mk_x="Tổng nhập khẩu từ Việt Nam (tỷ USD, thang log)",
  mk_y="Tỷ lệ quan hệ sống từ 5 năm trở lên (%)",
  mk_note="Kích thước bong bóng = số quan hệ · 12 thị trường lớn nhất",
  cc_m="5 thị trường lớn nhất", cc_p="10 mặt hàng lớn nhất",
  cc_y="Phần trăm tổng giá trị xuất khẩu",
  du_y="Số quan hệ", du_note="Hơn một nửa quan hệ\nchỉ tồn tại đúng một năm",
  sc_eu="Liên minh châu Âu\n2003–2023", sc_uk="Vương quốc Anh\n2003–2023",
  sc_gl="Toàn cầu\n147 thị trường",
  sc_k1="Số quan sát", sc_k2="Số quan hệ", sc_k3="Số lần chấm dứt", sc_k4="Số nhóm hàng",
  q_a="Bao nhiêu phần dữ liệu có giá trị", q_b="Đo đúng năm hay phải mượn năm khác",
  q_tar="Thuế nhập khẩu", q_ntm="Rào cản phi thuế", q_grav="Khoảng cách & thể chế",
  q_exact="đo đúng năm", q_other="mượn từ năm khác",
  hz_x="Thay đổi rủi ro chấm dứt khi yếu tố đó tăng lên (%)",
  bg1="Cốt lõi", bg2="Chính sách", bg3="Bối cảnh", bg4="Rào cản"),
"en": dict(sec=SEC_EN, blocks=BLOCKS_EN, haz=HAZ_EN, cov=COV_EN,
  s_y="USD million per year", s_peak="Peak USD 1.92 million", s_first="First year: USD 19 thousand",
  s_end="Last order", s_gone="no orders at all",
  t_r1="Germany · one apparel line", t_r2="Germany · another apparel line",
  t_cens="still selling when the data stops",
  t_n1="sold for 17 straight years, then stopped", t_n2="sold, stopped, sold again — five times",
  fl_y1="Active export relationships", fl_y2="Each year",
  fl_new="newly opened", fl_exit="ended",
  km_all="All", km_fta="With agreement", km_no="No agreement",
  km_x="Years the relationship has lasted", km_y="Share still selling",
  sz_q1="Smallest quarter", sz_q2="Small quarter", sz_q3="Large quarter", sz_q4="Largest quarter",
  se_x1="Share of relationships lasting five years or more",
  se_x2="Total exports 2003–2025 (USD billion)",
  mp_x="Total exports (USD billion, log scale)",
  mp_y="Share lasting five years or more (%)",
  mp_note="Bubble size = total value · orange = large but fragile",
  mk_x="Total imports from Viet Nam (USD billion, log scale)",
  mk_y="Share lasting five years or more (%)",
  mk_note="Bubble size = number of relationships · 12 largest markets",
  cc_m="Top 5 markets", cc_p="Top 10 products",
  cc_y="Percent of total export value",
  du_y="Number of relationships", du_note="More than half last\nexactly one year",
  sc_eu="European Union\n2003–2023", sc_uk="United Kingdom\n2003–2023",
  sc_gl="Global\n147 markets",
  sc_k1="Observations", sc_k2="Relationships", sc_k3="Endings", sc_k4="Product groups",
  q_a="How much of the data has a value", q_b="Measured in the right year, or borrowed",
  q_tar="Import tariffs", q_ntm="Non-tariff barriers", q_grav="Distance & institutions",
  q_exact="right year", q_other="borrowed from another year",
  hz_x="Change in the risk of ending when the factor increases (%)",
  bg1="Core", bg2="Policy", bg3="Context", bg4="Barriers"),
}
